# Generated by Django 4.2.3 on 2023-07-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPegasus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textak',
            name='mtn1',
            field=models.CharField(default='sh', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textak',
            name='mtn2',
            field=models.CharField(default='sh', max_length=200),
            preserve_default=False,
        ),
    ]
