# Generated by Django 4.2.3 on 2023-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPegasus', '0002_textak_mtn1_textak_mtn2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textak',
            name='mtn1',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='textak',
            name='mtn2',
            field=models.CharField(max_length=400),
        ),
    ]
