# Generated by Django 4.2.3 on 2023-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPegasus', '0003_alter_textak_mtn1_alter_textak_mtn2'),
    ]

    operations = [
        migrations.AddField(
            model_name='textak',
            name='mtn3',
            field=models.CharField(default='fffff', max_length=400),
            preserve_default=False,
        ),
    ]
