# Generated by Django 4.2.3 on 2023-07-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPegasus', '0004_textak_mtn3'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mtn_kol', models.CharField(max_length=400)),
                ('lnk_a', models.CharField(max_length=150)),
            ],
        ),
    ]
