# Generated by Django 4.2.3 on 2023-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPegasus', '0008_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='BlogPegasus/static/blog/img'),
        ),
    ]
